trigger:
  - master

pool:
  name: Hosted Ubuntu 1604

pool:
  name: Azure Pipelines
steps:
- task: Docker@2
  inputs:
    containerRegistry: 'kevinccbsg docker hub'
    repository: 'Curso Guidesmiths'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'

- task: PublishBuildArtifacts@1
    displayName: "Publish Artifact: drop"
    inputs:
      PathtoPublish: .helm